### ISSUE TITLE
User Story

### ISSUE THREAD

**Issue by Dawesie** [Dawesie/learning_agile#3]
In order to  **give additional information to given topic ** as a  **runner ** I can  **add a comment before submitting my vote**

## **Acceptance Criteria**
- **Acceptance Criteria 1:** There is a box to submit additional comments. 
- **Acceptance Criteria 2:** The box should be below the poll options.
- **Acceptance Criteria 3:** The maximum number of characters should be indicated.
- **Acceptance Criteria 4:** There should be a count to show number of characters remaining.
## **Task**
- [ ] Task 1: Create an input box for text to be added using HTML and CSS. 
- [ ] Task 2: Use HTML and CSS to portion the input below pole options. 
- [ ] Task 3: Use JavaScript to calculate the number of characters left.
