### ISSUE TITLE
User Story

### ISSUE THREAD

**Issue by Dawesie** [Dawesie/learning_agile#4]
In order to **give feedback from the poll taken** as an **administrator **, I can ** count the votes**

##  **Acceptance Criteria**
- **Acceptance Criteria 1** The total number of votes must be tallied. 
- **Acceptance Criteria 2** The total number of votes can be calculated as a percentage of the number of members of the club.  
- **Acceptance Criteria 3** Each poll option can be determined as a percentage of the total. 
- **Acceptance Criteria 4** Final results is tabulated. 

## **Tasks**
- [ ] **Task 1:** Use JavaScript to tally the total number of votes.
- [ ] **Task 2:** Calculate votes cast as a percentage of total number of members in the club. 
- [ ] **Task 3:** Calculate total of each pole as a percentage of total votes.
- [ ] **Task 4:** Tabulate overall findings of the poll.
- [ ] **Task 3:** Test functionality.
